Sprint 3
xczdenis/middle.messenger.praktikum.yandex pull request #12
Opened 2022-05-31 07:14 UTC by xczdenis

Примечание по поводу тестов: тесты есть, но покрыто не абсолютно все. Есть тесты на роутер, компонент, ApiClient. Поскольку главная задача курса - это разобраться с механизмом - с механизмом разобрался. Остальная работа по написанию тестов достаточно монотонная

2022-05-31 15:28 UTC, podlovchenko requested changes
Привет)
1. Не получилось запустить командой npm run start
<img width="589" alt="Снимок экрана 2022-05-31 в 18 22 58" src="https://user-images.githubusercontent.com/22602747/171210903-df6ceca7-b4f3-414d-a99c-ddc5576342d0.png">
2. Нет редиректа на страницу чатов, если пользователь уже в системе
3. Не получилось отправить сообщения в чате
4. Закомментированный код в проекте лучше не оставлять

2022-05-31 19:57 UTC, xczdenis commented
> Привет)
> 
> 1. Не получилось запустить командой npm run start
> 
> <img alt="Снимок экрана 2022-05-31 в 18 22 58" width="589" src="https://user-images.githubusercontent.com/22602747/171210903-df6ceca7-b4f3-414d-a99c-ddc5576342d0.png">
> 
> 2. Нет редиректа на страницу чатов, если пользователь уже в системе 3. Не получилось отправить сообщения в чате 4. Закомментированный код в проекте лучше не оставлять

Что-то я запутался с коммитами... После того как я пофиксил замечания, мне же не надо создавать новый Pull request? Судя по всему, в этом PR уже есть мой коммит, в котором фиксятся указанные баги.
1. done
2. done
3. done (нужно создать новый чат, а потом кликнуть по нему - чат должен стать активным - в списке чатов он покрасится в голубой цвет, тогда можно отправлять сообщения)
4. done (пробежался по всем файлами, закоменченый код постарался везде убрать)

2022-06-01 08:16 UTC, podlovchenko commented
Все правильно, если делаешь исправления в той же ветке, то они будут в пулл реквесте
Спасибо за правки, работу принимаю)

2022-06-01 08:16 UTC, podlovchenko approved these changes

2022-06-01 08:29 UTC, merged